// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPlolt2oZUOlpY4EeO5a81dYotkgqyT6A',
    appId: '1:126109345475:web:26dc9de55a2e069eb9e476',
    messagingSenderId: '126109345475',
    projectId: 'money-tracker-d13e0',
    authDomain: 'money-tracker-d13e0.firebaseapp.com',
    storageBucket: 'money-tracker-d13e0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-wIoA0At793eZrUaPOFqkyIT288ew9QU',
    appId: '1:126109345475:android:70b33a10be8fe5c5b9e476',
    messagingSenderId: '126109345475',
    projectId: 'money-tracker-d13e0',
    storageBucket: 'money-tracker-d13e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsmz7-BHVujnyDL2F5idCFcJh_gYatnFw',
    appId: '1:126109345475:ios:a03edee549142f36b9e476',
    messagingSenderId: '126109345475',
    projectId: 'money-tracker-d13e0',
    storageBucket: 'money-tracker-d13e0.firebasestorage.app',
    iosBundleId: 'com.example.moneyTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsmz7-BHVujnyDL2F5idCFcJh_gYatnFw',
    appId: '1:126109345475:ios:a03edee549142f36b9e476',
    messagingSenderId: '126109345475',
    projectId: 'money-tracker-d13e0',
    storageBucket: 'money-tracker-d13e0.firebasestorage.app',
    iosBundleId: 'com.example.moneyTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPlolt2oZUOlpY4EeO5a81dYotkgqyT6A',
    appId: '1:126109345475:web:3fe15c10cb03c0abb9e476',
    messagingSenderId: '126109345475',
    projectId: 'money-tracker-d13e0',
    authDomain: 'money-tracker-d13e0.firebaseapp.com',
    storageBucket: 'money-tracker-d13e0.firebasestorage.app',
  );

}